# Generated by Django 4.2.16 on 2026-10-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityInformation',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='place',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='placephoto',
            name='place',
        ),
        migrations.RemoveField(
            model_name='review',
            name='place',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='ItineraryItem',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='PlacePhoto',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
